<script lang="ts">
	import { m } from '$lib/paraglide/messages.js';import { href } from '$lib/link';import type { CommunityMapCounters } from '$lib/server/generated/chimps/types.gen';let{data}=$props();const n=new Intl.NumberFormat();const pct=new Intl.NumberFormat(undefined,{style:'percent',maximumFractionDigits:1});const counterRows: Array<[keyof CommunityMapCounters,string]>=$derived([['plays',m.community_maps_plays()],['wins',m.community_maps_wins()],['losses',m.community_maps_losses()],['playsUnique',m.community_maps_unique_plays()],['winsUnique',m.community_maps_unique_wins()],['lossesUnique',m.community_maps_unique_losses()]]);function trendRate(t:{wins:number;losses:number}){const total=t.wins+t.losses;return total?pct.format(t.wins/total):m.community_maps_no_outcomes()}
</script>
<svelte:head><title>{data.map.name} · chimps.gg</title></svelte:head>
<article class="map page-shell">
	<header><img src={data.map.mapUrl} alt="" /><div><a href={href('/community-maps')}>{m.community_maps_back()}</a><h1>{data.map.name}</h1><p><code>{data.map.mapCode}</code> · {m.community_maps_created_version({version:data.map.creationVersion})}</p>{#if data.map.creator}<a href={href(`/players/${data.map.creator.userId}`)}>{m.community_maps_by({name:data.map.creator.displayName})}</a>{/if}</div></header>
	<section class="headline"><div><strong>{data.map.winRate===null?m.community_maps_no_outcomes():pct.format(data.map.winRate)}</strong><span>{m.community_maps_decisive_rate()}</span></div><p>{m.community_maps_decisive_explain()}</p></section>
	<section class="counters" aria-label={m.community_maps_lifetime()}><h2>{m.community_maps_lifetime()}</h2>{#each counterRows as [key,label]}<div><strong>{n.format(data.map.counters[key])}</strong><span>{label}</span></div>{/each}</section>
	<section class="trends"><h2>{m.community_maps_by_version()}</h2>{#if data.map.trends.length}<div class="trend-list">{#each data.map.trends as trend}<article><header><h3>v{trend.version}</h3>{#if trend.sinceTrackingBegan}<span>{m.community_maps_since_tracking()}</span>{/if}</header><strong>{trendRate(trend)}</strong><p>{n.format(trend.plays)} {m.community_maps_plays().toLowerCase()} · {n.format(trend.wins)} {m.community_maps_wins().toLowerCase()} · {n.format(trend.losses)} {m.community_maps_losses().toLowerCase()}</p><small>{n.format(trend.playsUnique)} / {n.format(trend.winsUnique)} / {n.format(trend.lossesUnique)} {m.community_maps_unique_order()}</small></article>{/each}</div>{:else}<p class="empty">{m.community_maps_waiting_snapshot()}</p>{/if}{#if data.map.transitions.length}<details><summary>{m.community_maps_transitions({count:data.map.transitions.length})}</summary><ul>{#each data.map.transitions as transition}<li>v{transition.fromVersion} → v{transition.toVersion}: {m.community_maps_transition_excluded()}</li>{/each}</ul></details>{/if}</section>
	<footer>{m.community_maps_tracking_since({date:new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(data.map.firstObservedAt))})} · {m.community_maps_refreshed({date:new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(data.map.lastSyncedAt))})}</footer>
</article>
<style>.map{display:grid;gap:var(--space-4);padding-block:var(--space-6)}.map>header{display:grid;grid-template-columns:minmax(16rem,1fr) 1fr;gap:var(--space-4);align-items:center}.map>header img{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:var(--radius-lg);border:1px solid var(--border)}h1,h2,h3,p{margin:0}h1,h2,h3{font-family:var(--font-display)}h1{font-size:clamp(2rem,5vw,3.5rem)}.map>header div{display:grid;gap:.5rem}code{font-family:var(--font-mono)}.headline{display:flex;align-items:center;gap:var(--space-4);padding:var(--space-4);border-radius:var(--radius-lg);background:var(--brand-soft)}.headline div{display:grid}.headline strong{font-family:var(--font-display);font-size:2.5rem}.headline span,.headline p{color:var(--fg-muted)}.counters{display:grid;grid-template-columns:repeat(6,1fr);gap:var(--space-2)}.counters h2{grid-column:1/-1}.counters div{display:grid;padding:var(--space-3);border:1px solid var(--border);border-radius:var(--radius-md);background:var(--surface-raised)}.counters strong{font-size:1.25rem}.counters span,small{color:var(--fg-muted);font-size:var(--text-meta)}.trends{display:grid;gap:var(--space-3)}.trend-list{display:grid;grid-template-columns:repeat(3,1fr);gap:var(--space-2)}.trend-list article{display:grid;gap:.35rem;padding:var(--space-3);border:1px solid var(--border);border-radius:var(--radius-md);background:var(--surface-raised)}.trend-list header{display:flex;justify-content:space-between;gap:1rem}.trend-list header span{font-size:var(--text-meta);color:var(--accent)}.trend-list>article>strong{font-size:1.5rem}.empty{padding:var(--space-3);border-radius:var(--radius-md);background:var(--surface);color:var(--fg-muted)}footer{color:var(--fg-muted);font-size:var(--text-meta)}@media(max-width:60rem){.counters{grid-template-columns:repeat(3,1fr)}.trend-list{grid-template-columns:repeat(2,1fr)}}@media(max-width:42rem){.map>header{grid-template-columns:1fr}.headline{align-items:flex-start;flex-direction:column}.counters,.trend-list{grid-template-columns:1fr 1fr}}@media(max-width:30rem){.counters,.trend-list{grid-template-columns:1fr}}</style>
