// Handwritten database types. Keep in sync with supabase/migrations/ — update
// these in the same change as any migration.

export type MapDifficulty = 'Beginner' | 'Intermediate' | 'Advanced' | 'Expert';
// Heroes are towers with category 'Hero' (no separate heroes table).
export type TowerCategory = 'Primary' | 'Military' | 'Magic' | 'Support' | 'Hero';
export type StrategyStatus = 'draft' | 'ready' | 'archived';
export type StepAction = 'place' | 'upgrade' | 'sell' | 'retarget' | 'other';

export type MapRow = {
	id: number;
	name: string;
	difficulty: MapDifficulty | null;
	image_url: string | null;
	nk_map_id: string;
	nk_image_url: string | null;
	plays: number | null;
	wins: number | null;
	upvotes: number | null;
	last_synced_at: string | null;
	created_at: string;
	updated_at: string;
}

export type MapInsert = {
	name: string;
	difficulty?: MapDifficulty | null;
	image_url?: string | null;
	nk_map_id: string;
	nk_image_url?: string | null;
	plays?: number | null;
	wins?: number | null;
	upvotes?: number | null;
	last_synced_at?: string | null;
}

export type TowerRow = {
	id: number;
	name: string;
	category: TowerCategory;
	base_cost: number | null;
	icon_path: string;
}

export type TowerInsert = {
	name: string;
	category: TowerCategory;
	base_cost?: number | null;
	icon_path: string;
}

export type GameModeRow = {
	id: number;
	name: string;
}

export type GameModeInsert = {
	name: string;
}

export type StrategyRow = {
	id: number;
	map_id: number;
	game_mode_id: number;
	title: string;
	description: string | null;
	hero_id: number | null;
	source_url: string | null;
	verified_version: string | null;
	exec_difficulty: number | null;
	status: StrategyStatus;
	score: number | null;
	created_at: string;
	updated_at: string;
}

export type StrategyInsert = {
	map_id: number;
	game_mode_id: number;
	title: string;
	description?: string | null;
	hero_id?: number | null;
	source_url?: string | null;
	verified_version?: string | null;
	exec_difficulty?: number | null;
	status?: StrategyStatus;
	score?: number | null;
}

export type PlacementRow = {
	id: number;
	strategy_id: number;
	tower_id: number;
	pos_x: number;
	pos_y: number;
	final_path: string | null;
	label: string | null;
	notes: string | null;
}

export type PlacementInsert = {
	strategy_id: number;
	tower_id: number;
	pos_x: number;
	pos_y: number;
	final_path?: string | null;
	label?: string | null;
	notes?: string | null;
}

export type StepRow = {
	id: number;
	strategy_id: number;
	placement_id: number | null;
	round_number: number;
	action: StepAction;
	target_path: string | null;
	description: string | null;
	order_index: number;
}

export type StepInsert = {
	strategy_id: number;
	placement_id?: number | null;
	round_number: number;
	action: StepAction;
	target_path?: string | null;
	description?: string | null;
	order_index: number;
}

// supabase-js Database interface so createClient<Database>() gives typed
// .from() calls. id/created_at/updated_at are generated by the database and
// therefore absent from Insert types.
export type Database = {
	public: {
		Tables: {
			maps: {
				Row: MapRow;
				Insert: MapInsert;
				Update: Partial<MapInsert>;
				Relationships: [];
			};
			towers: {
				Row: TowerRow;
				Insert: TowerInsert;
				Update: Partial<TowerInsert>;
				Relationships: [];
			};
			game_modes: {
				Row: GameModeRow;
				Insert: GameModeInsert;
				Update: Partial<GameModeInsert>;
				Relationships: [];
			};
			strategies: {
				Row: StrategyRow;
				Insert: StrategyInsert;
				Update: Partial<StrategyInsert>;
				Relationships: [];
			};
			placements: {
				Row: PlacementRow;
				Insert: PlacementInsert;
				Update: Partial<PlacementInsert>;
				Relationships: [];
			};
			steps: {
				Row: StepRow;
				Insert: StepInsert;
				Update: Partial<StepInsert>;
				Relationships: [];
			};
		};
		Views: Record<string, never>;
		Functions: {
			reorder_steps: {
				Args: { p_strategy_id: number; p_step_ids: number[] };
				Returns: undefined;
			};
		};
		Enums: Record<string, never>;
		CompositeTypes: Record<string, never>;
	};
}
