// Handwritten database types. Keep in sync with supabase/migrations/ — update
// these in the same change as any migration.

export type MapDifficulty = 'Beginner' | 'Intermediate' | 'Advanced' | 'Expert';
// Heroes are towers with category 'Hero' (no separate heroes table).
export type TowerCategory = 'Primary' | 'Military' | 'Magic' | 'Support' | 'Hero';
export type StrategyStatus = 'draft' | 'ready' | 'archived';
export type StepAction = 'place' | 'upgrade' | 'sell' | 'retarget' | 'other';

export type MapRow = {
	id: number;
	name: string;
	difficulty: MapDifficulty | null;
	image_url: string | null;
	nk_map_id: string;
	nk_image_url: string | null;
	plays: number | null;
	wins: number | null;
	upvotes: number | null;
	last_synced_at: string | null;
	created_at: string;
	updated_at: string;
}

export type NkPlayerRow = {
	user_id: string;
	display_name: string;
	rank: number;
	veteran_rank: number;
	achievements: number;
	most_experienced_monkey: string;
	highest_round: number;
	avatar_url: string | null;
	banner_url: string | null;
	followers: number;
	bloons_popped: number;
	game_count: number;
	games_won: number;
	profile_data: Record<string, unknown>;
	first_observed_at: string;
	last_synced_at: string;
	updated_at: string;
};

export type CommunityMapRow = {
	map_code: string;
	name: string;
	creator_user_id: string | null;
	created_at: string;
	creation_version: string;
	map_url: string;
	plays: number;
	wins: number;
	losses: number;
	plays_unique: number;
	wins_unique: number;
	losses_unique: number;
	first_observed_at: string;
	last_synced_at: string;
	updated_at: string;
};

export type CommunityMapSnapshotRow = {
	id: number;
	map_code: string;
	snapshot_date: string;
	captured_at: string;
	game_version: string;
	version_source_url: string;
	version_observed_at: string;
	plays: number;
	wins: number;
	losses: number;
	plays_unique: number;
	wins_unique: number;
	losses_unique: number;
};

export type NkVersionObservationRow = {
	id: number;
	game_version: string;
	source_url: string;
	observed_at: string;
};

type MapInsert = {
	name: string;
	difficulty?: MapDifficulty | null;
	image_url?: string | null;
	nk_map_id: string;
	nk_image_url?: string | null;
	plays?: number | null;
	wins?: number | null;
	upvotes?: number | null;
	last_synced_at?: string | null;
}

export type TowerRow = {
	id: number;
	name: string;
	category: TowerCategory;
	base_cost: number | null;
	icon_path: string;
	description: string | null;
	attack_style: string | null;
	xp_ratio: number | null;
	technical_description: string | null;
	profile_source_url: string | null;
}

type TowerInsert = {
	name: string;
	category: TowerCategory;
	base_cost?: number | null;
	icon_path: string;
	description?: string | null;
	attack_style?: string | null;
	xp_ratio?: number | null;
	technical_description?: string | null;
	profile_source_url?: string | null;
}

export type TowerSynergyRow = {
	id: number;
	tower_a_id: number;
	tower_b_id: number;
	description: string | null;
	created_at: string;
}

type TowerSynergyInsert = {
	tower_a_id: number;
	tower_b_id: number;
	description?: string | null;
};

export type GameModeRow = {
	id: number;
	name: string;
}

type GameModeInsert = {
	name: string;
}

export type StrategyRow = {
	id: number;
	map_id: number;
	game_mode_id: number;
	title: string;
	description: string | null;
	hero_id: number | null;
	source_url: string | null;
	// A database constraint requires this to be nonblank when status is 'ready';
	// it remains nullable for draft and archived strategies.
	verified_version: string | null;
	exec_difficulty: number | null;
	status: StrategyStatus;
	score: number | null;
	created_at: string;
	updated_at: string;
}

export type StrategyInsert = {
	map_id: number;
	game_mode_id: number;
	title: string;
	description?: string | null;
	hero_id?: number | null;
	source_url?: string | null;
	verified_version?: string | null;
	exec_difficulty?: number | null;
	status?: StrategyStatus;
	score?: number | null;
}

export type PlacementRow = {
	id: number;
	strategy_id: number;
	tower_id: number;
	pos_x: number;
	pos_y: number;
	final_path: string | null;
	label: string | null;
	notes: string | null;
}

export type PlacementInsert = {
	strategy_id: number;
	tower_id: number;
	pos_x: number;
	pos_y: number;
	final_path?: string | null;
	label?: string | null;
	notes?: string | null;
}

export type StepRow = {
	id: number;
	strategy_id: number;
	placement_id: number | null;
	round_number: number;
	action: StepAction;
	target_path: string | null;
	description: string | null;
	order_index: number;
}

export type StepInsert = {
	strategy_id: number;
	placement_id?: number | null;
	round_number: number;
	action: StepAction;
	target_path?: string | null;
	description?: string | null;
	order_index: number;
}

// supabase-js Database interface so createClient<Database>() gives typed
// .from() calls. id/created_at/updated_at are generated by the database and
// therefore absent from Insert types.
export type Database = {
	public: {
		Tables: {
			nk_version_observations: {
				Row: NkVersionObservationRow;
				Insert: Omit<NkVersionObservationRow, 'id'>;
				Update: never;
				Relationships: [];
			};
			nk_players: {
				Row: NkPlayerRow;
				Insert: Omit<NkPlayerRow, 'first_observed_at' | 'last_synced_at' | 'updated_at'> & Partial<Pick<NkPlayerRow, 'first_observed_at' | 'last_synced_at' | 'updated_at'>>;
				Update: Partial<NkPlayerRow>;
				Relationships: [];
			};
			community_maps: {
				Row: CommunityMapRow;
				Insert: Omit<CommunityMapRow, 'first_observed_at' | 'last_synced_at' | 'updated_at'> & Partial<Pick<CommunityMapRow, 'first_observed_at' | 'last_synced_at' | 'updated_at'>>;
				Update: Partial<CommunityMapRow>;
				Relationships: [{ foreignKeyName: 'community_maps_creator_user_id_fkey'; columns: ['creator_user_id']; isOneToOne: false; referencedRelation: 'nk_players'; referencedColumns: ['user_id'] }];
			};
			community_map_snapshots: {
				Row: CommunityMapSnapshotRow;
				Insert: Omit<CommunityMapSnapshotRow, 'id'>;
				Update: never;
				Relationships: [{ foreignKeyName: 'community_map_snapshots_map_code_fkey'; columns: ['map_code']; isOneToOne: false; referencedRelation: 'community_maps'; referencedColumns: ['map_code'] }];
			};
			maps: {
				Row: MapRow;
				Insert: MapInsert;
				Update: Partial<MapInsert>;
				Relationships: [];
			};
			towers: {
				Row: TowerRow;
				Insert: TowerInsert;
				Update: Partial<TowerInsert>;
				Relationships: [];
			};
			tower_synergies: {
				Row: TowerSynergyRow;
				Insert: TowerSynergyInsert;
				Update: Partial<TowerSynergyInsert>;
				Relationships: [
					{
						foreignKeyName: 'tower_synergies_tower_a_id_fkey';
						columns: ['tower_a_id'];
						isOneToOne: false;
						referencedRelation: 'towers';
						referencedColumns: ['id'];
					},
					{
						foreignKeyName: 'tower_synergies_tower_b_id_fkey';
						columns: ['tower_b_id'];
						isOneToOne: false;
						referencedRelation: 'towers';
						referencedColumns: ['id'];
					}
				];
			};
			game_modes: {
				Row: GameModeRow;
				Insert: GameModeInsert;
				Update: Partial<GameModeInsert>;
				Relationships: [];
			};
			strategies: {
				Row: StrategyRow;
				Insert: StrategyInsert;
				Update: Partial<StrategyInsert>;
				Relationships: [
					{
						foreignKeyName: 'strategies_map_id_fkey';
						columns: ['map_id'];
						isOneToOne: false;
						referencedRelation: 'maps';
						referencedColumns: ['id'];
					},
					{
						foreignKeyName: 'strategies_game_mode_id_fkey';
						columns: ['game_mode_id'];
						isOneToOne: false;
						referencedRelation: 'game_modes';
						referencedColumns: ['id'];
					},
					{
						foreignKeyName: 'strategies_hero_id_fkey';
						columns: ['hero_id'];
						isOneToOne: false;
						referencedRelation: 'towers';
						referencedColumns: ['id'];
					}
				];
			};
			placements: {
				Row: PlacementRow;
				Insert: PlacementInsert;
				Update: Partial<PlacementInsert>;
				Relationships: [
					{
						foreignKeyName: 'placements_strategy_id_fkey';
						columns: ['strategy_id'];
						isOneToOne: false;
						referencedRelation: 'strategies';
						referencedColumns: ['id'];
					},
					{
						foreignKeyName: 'placements_tower_id_fkey';
						columns: ['tower_id'];
						isOneToOne: false;
						referencedRelation: 'towers';
						referencedColumns: ['id'];
					}
				];
			};
			steps: {
				Row: StepRow;
				Insert: StepInsert;
				Update: Partial<StepInsert>;
				Relationships: [
					{
						foreignKeyName: 'steps_strategy_id_fkey';
						columns: ['strategy_id'];
						isOneToOne: false;
						referencedRelation: 'strategies';
						referencedColumns: ['id'];
					},
					{
						foreignKeyName: 'steps_placement_id_fkey';
						columns: ['placement_id'];
						isOneToOne: false;
						referencedRelation: 'placements';
						referencedColumns: ['id'];
					}
				];
			};
		};
		Views: Record<string, never>;
		Functions: {
			get_public_heroes: {
				Args: Record<PropertyKey, never>;
				Returns: Array<{
					id: number;
					name: string;
					icon_path: string;
					guide_count: number;
				}>;
			};
			get_public_references: {
				Args: Record<PropertyKey, never>;
				Returns: {
					maps: Array<
						Pick<MapRow, 'id' | 'name' | 'difficulty' | 'image_url' | 'nk_image_url'>
					>;
					modes: Array<Pick<GameModeRow, 'id' | 'name'>>;
					heroes: Array<Pick<TowerRow, 'id' | 'name' | 'category' | 'icon_path'>>;
				};
			};
			get_public_strategy_versions: {
				Args: Record<PropertyKey, never>;
				Returns: Array<{ verified_version: string }>;
			};
			reorder_steps: {
				Args: { p_strategy_id: number; p_step_ids: number[] };
				Returns: undefined;
			};
			update_hero_profile: {
				Args: {
					p_hero_id: number;
					p_description: string | null;
					p_base_cost: number | null;
					p_attack_style: string | null;
					p_xp_ratio: number | null;
					p_technical_description: string | null;
					p_profile_source_url: string | null;
					p_synergy_tower_ids: number[];
					p_synergy_descriptions: string[];
				};
				Returns: undefined;
			};
		};
		Enums: Record<string, never>;
		CompositeTypes: Record<string, never>;
	};
}
